@Host = http://localhost:5000
 
### Login
# @name login
POST {{Host}}/api/auth/login
Content-Type: application/json
 
{
  "email": "xxxxxxxx@gmail.com",
  "password": "********"
}
 
###
 
### Get Rates
GET {{Host}}/api/rates
Authorization: Bearer {{login.response.body.$.token}}
 
###
 
GET {{Host}}/api/Values
 
###
 
### Dashboard Summary
GET {{Host}}/api/dashboard/summary
Authorization: Bearer {{login.response.body.$.token}}

###

### Dashboard Portfolio Metric
GET {{Host}}/api/dashboard/portfolio-composition
Authorization: Bearer {{login.response.body.$.token}}

###

### Dashboard Portfolio Value Over Time
GET {{Host}}/api/dashboard/portfolio-value-history
Authorization: Bearer {{login.response.body.$.token}}

###

