@ZakatVault.Api_HostAddress = http://localhost:8080

POST {{ZakatVault.Api_HostAddress}}/api/Auth/register/
Accept: application/json
Content-Type: application/json

{
  "name": "Mohammed Abdelhay",
  "email": "mamado2000@gmail.com",
  "password": "M@ro2008AC"
}

###

POST {{ZakatVault.Api_HostAddress}}/api/Auth/login/
Accept: application/json
Content-Type: application/json

{
  "email": "mamado2000@gmail.com",
  "password": "M@ro2008AC"
}

###